# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20181218_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
