# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nauczyciel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
    ]
