# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nauczyciel', '0002_remove_submission_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'zadania'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'zajecia'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'nauczyciele'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name_plural': 'rozwiazania'},
        ),
    ]
